### PR TITLE
Added spotbugs

### PR DESCRIPTION
**Pull request by judovana**
Commented out its inclusion during build, as it is ow quite failing
Canbe run (in individual modules) as mvn spotbugs:check

### CODE REVIEW

**Comment by judovana** [comment]
mvn spotbugs:check | grep clean
[ERROR] Medium: org.fakekoji.jobmanager.JenkinsCliWrapper.createManuallyUploadedJob(File, String) may fail to clean up java.io.InputStream [org.fakekoji.jobmanager.JenkinsCliWrapper, org.fakekoji.jobmanager.JenkinsCliWrapper] Obligation to clean up resource created at JenkinsCliWrapper.java:[line 241] is not dischargedPath continues at JenkinsCliWrapper.java:[line 242] OBL_UNSATISFIED_OBLIGATION
[ERROR] Medium: org.fakekoji.jobmanager.JenkinsCliWrapper.updateManuallyUpdatedJob(File, String) may fail to clean up java.io.InputStream [org.fakekoji.jobmanager.JenkinsCliWrapper, org.fakekoji.jobmanager.JenkinsCliWrapper] Obligation to clean up resource created at JenkinsCliWrapper.java:[line 257] is not dischargedPath continues at JenkinsCliWrapper.java:[line 258] OBL_UNSATISFIED_OBLIGATION



hmmm ot much leaked resources:-/

**Comment by judovana** [comment]
a jeste by to Ondra h. mohl dodat do summary-reportu...

**Comment by AurumTheEnd** [comment]
> a jeste by to Ondra H. mohl dodat do summary-reportu...

Mohl jsi mě `@`nout pro jednoduchost, ale nakonec jsem tenhle breadcrumb našel.

**Comment by judovana** [comment]
That was moreover note for myself, and hint for Our main reviwer... But thank you for being so watchful!

**Comment by judovana** [comment]
Also this PR should be rebased one the cache is merged

**Pull request merged**
