### PR TITLE
rename SshApiService, XmlRpcService and JavaClient classes, move Java…

### PR DESCRIPTION
**Pull request by oklinov**
…Client to test package

### CODE REVIEW

**Comment by judovana** [comment]
I have some objectins:
public class SshApiService  -> public class FileTransferService {
Is the service doinfg somethng else then scp? I doubt... Thus:
SshFileTransferService or ScpService

Same for:
public class XmlRpcService  -> public class KojiService {
is it doing something else then xmlrpc? I dont think so... Thus:
XmlRpcKojiLIkeService

As it is xmlrpc, which is based on koji api....

Otherwise I'm happy with the clean up you are doing. Thanx!
Thoughts?

**Comment by oklinov** [comment]
FileTransferService is in ssh package and KojiService in xmlrpc package. Doesn't that tell what these classes do?

**Comment by judovana** [comment]
Yes. Bu they stopped to tell the basic principle of how they do it

**Comment by judovana** [comment]
looks good by me.

**Pull request merged**
